/* db: ammdb, nome: luca, password: luca */

--tipoDiPost nome tabella
CREATE TABLE tipoDiPost(
    id_tipoDiPost INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, --chiave primaria
    nome_tipoDiPost VARCHAR(32) 
);

--utenti nome tabella
CREATE TABLE utente(
    utente_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, --chiave primaria
    nome VARCHAR(130), -- UNIQUE (vincolo integrità) permette che il nome sia univoco
    cognome VARCHAR(130),
    dataDiNascita VARCHAR(20),
    email VARCHAR(30) UNIQUE,
    password VARCHAR(30),
    urlFotoProfilo VARCHAR(128),
    frasePresentazione VARCHAR(600)
);

CREATE TABLE posts(
    id_post INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, /*chiave primaria*/
    testoPost VARCHAR(256),
    immaginePost VARCHAR(100),
    tipo INTEGER, --SI RIFERISCE ALL'ID DEL tipoDiPost ED CHIAVE ESTERNA
    FOREIGN KEY (tipo) REFERENCES tipoDiPost(id_tipoDiPost), --serve per creare una chiave esterna che si riferisce all'id di tipoDiPost
    autore INTEGER,
    FOREIGN KEY (autore) REFERENCES utente(utente_id) --serve per creare una chiave esterna che si riferisce all'id di utenti
);

CREATE TABLE gruppo(
    id_gruppo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_gruppo VARCHAR(100),
    fondatore INTEGER,
    FOREIGN KEY (fondatore) REFERENCES utente (utente_id)
);

CREATE TABLE gruppo_utente(
    id_gruppo INTEGER,
    FOREIGN KEY (id_gruppo) REFERENCES gruppo (id_gruppo),
    utente_id INTEGER,
    FOREIGN KEY (utente_id) REFERENCES utente (utente_id)
);

/******** POPOLAMENTO DELLA TABELLA UTENTI *********/
INSERT INTO utente(utente_id, nome, cognome, dataDiNascita, email, password, urlFotoProfilo, frasePresentazione)
VALUES (default,
	'luca',
        'fadda',
         null,
        'luca@hotmail.it',
	'123',
	'img/luca.jpg',
        'ciao belli');

INSERT INTO utente(utente_id, nome, cognome, dataDiNascita, email, password, urlFotoProfilo, frasePresentazione)
VALUES (default,
	'alessia',
        'selis',
        '18-12-1995',
        'alessia@hotmail.it',
	'123',
	'img/alessia.jpg',
        'ciao a tutti');

INSERT INTO utente(utente_id, nome, cognome, dataDiNascita, email, password, urlFotoProfilo, frasePresentazione)
VALUES (default,
	'andrea',
        'amadori',
        '10-01-1992',
        'andrea@hotmail.it',
	'123',
	'img/andrea.jpg',
        null);

INSERT INTO utente(utente_id, nome, cognome, dataDiNascita, email, password, urlFotoProfilo, frasePresentazione)
VALUES (default,
	'emanuel',
        'fois',
        '20-07-1993',
        'emanuel@hotmail.it',
	'123',
	'img/emanuel.jpg',
        null);

INSERT INTO utente(utente_id, nome, cognome, dataDiNascita, email, password, urlFotoProfilo, frasePresentazione)
VALUES (default,
	'fabrizio',
        'basciu',
        '12-05-1993',
        'fabrizio@hotmail.it',
	'123',
	'img/fabrizio.jpg',
        null);

/******** POPOLAMENTO DELLA TABELLA tipoDiPost *********/
INSERT INTO tipoDiPost(id_tipoDiPost, nome_tipoDiPost)
VALUES (default, 'TEXT');

INSERT INTO tipoDiPost(id_tipoDiPost, nome_tipoDiPost)
VALUES (default, 'URL');

/******** POPOLAMENTO DELLA TABELLA posts *********/

/* luca */
INSERT INTO posts(id_post, testoPost, immaginePost, tipo, autore)
VALUES (default,
        'ciao sono luca, ho 23 anni, studio informatica e ho una dipendenza per i pomodorini',
        'immagini/spiaggia.jpg',
        2,
        1);

/* alessia */
INSERT INTO posts(id_post, testoPost, immaginePost, tipo, autore)
VALUES (default,
        'ciao sono Alessia e sono la fidazata di Luca',
        'immagini/pizza.jpg',
        2,
        2);

/* andrea */
INSERT INTO posts(id_post, testoPost, immaginePost, tipo, autore)
VALUES (default,
        'ciao sono andrea, ho 25 anni e studio scienze politiche',
        'immagini/arrow.jpg',
        2,
        3);

/* emanuele */
INSERT INTO posts(id_post, testoPost, immaginePost, tipo, autore)
VALUES (default,
        'ciao sono emanuele e questo sono io da bambino:',
        'immagini/tasto.png',
        2,
        4);

/* fabrizio */
INSERT INTO posts(id_post, testoPost, immaginePost, tipo, autore)
VALUES (default,
        'ciao sono fabrizio, ho 24 anni e ho una dipendenza per il computer',
        'immagini/ovali.jpg',
        2,
        5);

/* popolamento gruppi */

INSERT INTO gruppo(id_gruppo,nome_gruppo,fondatore)
VALUES(
        default,
        'Informatica',
        1);

INSERT INTO gruppo(id_gruppo,nome_gruppo,fondatore)
VALUES(
        default,
        'Economia Aziendale',
        2);

INSERT INTO gruppo(id_gruppo,nome_gruppo,fondatore)
VALUES(
        default,
        'Scienze Politiche',
        3);

INSERT INTO gruppo(id_gruppo,nome_gruppo,fondatore)
VALUES(
        default,
        'Lavoratore',
        5);

INSERT INTO gruppo_utente(id_gruppo, utente_id)
VALUES (1,1),
       (1,4),
       (2,2),
       (3,3),
       (4,5);


